//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApptSoftEntities : DbContext
    {
        public ApptSoftEntities()
            : base("name=ApptSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Address> C_Address { get; set; }
        public virtual DbSet<C_Client_01> C_Client_01 { get; set; }
        public virtual DbSet<C_emp_01> C_emp_01 { get; set; }
        public virtual DbSet<Company_Master> Company_Master { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Empl> Empls { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<tblAMC> tblAMCs { get; set; }
        public virtual DbSet<tblComplaint> tblComplaints { get; set; }
        public virtual DbSet<tblCorpusFund> tblCorpusFunds { get; set; }
        public virtual DbSet<tblExpens> tblExpenses { get; set; }
        public virtual DbSet<tblIncome> tblIncomes { get; set; }
        public virtual DbSet<tblMaintenance> tblMaintenances { get; set; }
        public virtual DbSet<tblResident> tblResidents { get; set; }
        public virtual DbSet<tblTenant> tblTenants { get; set; }
        public virtual DbSet<tblVisitor> tblVisitors { get; set; }
        public virtual DbSet<Vendor_Master> Vendor_Master { get; set; }
        public virtual DbSet<C_emp> C_emp { get; set; }
        public virtual DbSet<C_emp3411> C_emp3411 { get; set; }
        public virtual DbSet<PurchaseOrder_Details> PurchaseOrder_Details { get; set; }
        public virtual DbSet<JobCard_Details> JobCard_Details { get; set; }
        public virtual DbSet<JobCard_Master> JobCard_Master { get; set; }
        public virtual DbSet<JobCard_Production_Tracking> JobCard_Production_Tracking { get; set; }
        public virtual DbSet<Production_Operations> Production_Operations { get; set; }
        public virtual DbSet<tblDispatch> tblDispatches { get; set; }
        public virtual DbSet<tblDispatchContractor> tblDispatchContractors { get; set; }
        public virtual DbSet<tblContractor> tblContractors { get; set; }
        public virtual DbSet<tblsummaryreport> tblsummaryreports { get; set; }
    }
}
