
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class C_Client_01
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public C_Client_01()
    {

        this.C_Address = new HashSet<C_Address>();

    }


    public int Client_ID { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public Nullable<int> Age { get; set; }

    public string Country { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<C_Address> C_Address { get; set; }

}

}
