//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_emp_01
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string department { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
