
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class C_emp
{

    public int emp_id { get; set; }

    public string emp_name { get; set; }

    public string mobile { get; set; }

    public Nullable<int> dept_id { get; set; }

    public string email { get; set; }

    public string address { get; set; }

    public Nullable<decimal> salary { get; set; }

    public Nullable<System.DateTime> Dob { get; set; }

    public Nullable<System.DateTime> doj { get; set; }

}

}
