
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class FIBC_FabricDetails
{

    public int FabricId { get; set; }

    public Nullable<int> JobCardId { get; set; }

    public string Body_Colour { get; set; }

    public Nullable<decimal> Body_Width { get; set; }

    public Nullable<decimal> Body_CutLen { get; set; }

    public Nullable<decimal> Body_GSM { get; set; }

    public Nullable<decimal> Body_Lam { get; set; }

    public Nullable<decimal> Body_Total { get; set; }

    public Nullable<decimal> Body_CutWt { get; set; }

    public Nullable<decimal> Body_TotalMtr { get; set; }

    public string Side_Colour { get; set; }

    public Nullable<decimal> Side_Width { get; set; }

    public Nullable<decimal> Side_CutLen { get; set; }

    public Nullable<decimal> Side_GSM { get; set; }

    public Nullable<decimal> Side_Lam { get; set; }

    public Nullable<decimal> Side_Total { get; set; }

    public Nullable<decimal> Side_CutWt { get; set; }

    public Nullable<decimal> Side_TotalMtr { get; set; }

    public string Top_Colour { get; set; }

    public Nullable<decimal> Top_Width { get; set; }

    public Nullable<decimal> Top_CutLen { get; set; }

    public Nullable<decimal> Top_GSM { get; set; }

    public Nullable<decimal> Top_Lam { get; set; }

    public Nullable<decimal> Top_Total { get; set; }

    public Nullable<decimal> Top_CutWt { get; set; }

    public Nullable<decimal> Top_TotalMtr { get; set; }

    public string Flap_Colour { get; set; }

    public Nullable<decimal> Flap_Width { get; set; }

    public Nullable<decimal> Flap_CutLen { get; set; }

    public Nullable<decimal> Flap_GSM { get; set; }

    public Nullable<decimal> Flap_Lam { get; set; }

    public Nullable<decimal> Flap_Total { get; set; }

    public Nullable<decimal> Flap_CutWt { get; set; }

    public Nullable<decimal> Flap_TotalMtr { get; set; }

    public string FS_Type { get; set; }

    public string FS_Colour { get; set; }

    public Nullable<decimal> FS_Width { get; set; }

    public Nullable<decimal> FS_CutLen { get; set; }

    public Nullable<decimal> FS_GSM { get; set; }

    public Nullable<decimal> FS_Lam { get; set; }

    public Nullable<decimal> FS_Total { get; set; }

    public Nullable<decimal> FS_CutWt { get; set; }

    public Nullable<decimal> FS_TotalMtr { get; set; }

    public string SKT_Colour { get; set; }

    public Nullable<decimal> SKT_Width { get; set; }

    public Nullable<decimal> SKT_CutLen { get; set; }

    public Nullable<decimal> SKT_GSM { get; set; }

    public Nullable<decimal> SKT_Lam { get; set; }

    public Nullable<decimal> SKT_Total { get; set; }

    public Nullable<decimal> SKT_CutWt { get; set; }

    public Nullable<decimal> SKT_TotalMtr { get; set; }

    public string DS_Type { get; set; }

    public string DS_Colour { get; set; }

    public Nullable<decimal> DS_Width { get; set; }

    public Nullable<decimal> DS_CutLen { get; set; }

    public Nullable<decimal> DS_GSM { get; set; }

    public Nullable<decimal> DS_Lam { get; set; }

    public Nullable<decimal> DS_Total { get; set; }

    public Nullable<decimal> DS_CutWt { get; set; }

    public Nullable<decimal> DS_TotalMtr { get; set; }

    public string Iris_Colour { get; set; }

    public Nullable<decimal> Iris_Width { get; set; }

    public Nullable<decimal> Iris_CutLen { get; set; }

    public Nullable<decimal> Iris_GSM { get; set; }

    public Nullable<decimal> Iris_Lam { get; set; }

    public Nullable<decimal> Iris_Total { get; set; }

    public Nullable<decimal> Iris_CutWt { get; set; }

    public Nullable<decimal> Iris_TotalMtr { get; set; }

    public string Extra_Colour { get; set; }

    public Nullable<decimal> Extra_Width { get; set; }

    public Nullable<decimal> Extra_CutLen { get; set; }

    public Nullable<decimal> Extra_GSM { get; set; }

    public Nullable<decimal> Extra_Lam { get; set; }

    public Nullable<decimal> Extra_Total { get; set; }

    public Nullable<decimal> Extra_CutWt { get; set; }

    public Nullable<decimal> Extra_TotalMtr { get; set; }

}

}
