
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class FIBC_JobCard
{

    public int JobCardId { get; set; }

    public string Customer { get; set; }

    public string PurchaseNo { get; set; }

    public string RefNo { get; set; }

    public string BagType { get; set; }

    public string StitchingType { get; set; }

    public string PrintSC { get; set; }

    public Nullable<int> OrderQty { get; set; }

    public Nullable<decimal> BagSizeL { get; set; }

    public Nullable<decimal> BagSizeW { get; set; }

    public Nullable<decimal> BagSizeH { get; set; }

    public string FillingType { get; set; }

    public Nullable<decimal> FillingDaya { get; set; }

    public Nullable<decimal> FillingHeight { get; set; }

    public string DischargeType { get; set; }

    public Nullable<decimal> DischargeDaya { get; set; }

    public Nullable<decimal> DischargeHeight { get; set; }

    public Nullable<decimal> FabricGSM { get; set; }

    public Nullable<decimal> FabricCoatingGSM { get; set; }

    public string FabricColor { get; set; }

    public string LoopAttType { get; set; }

    public Nullable<decimal> LoopGM { get; set; }

    public Nullable<decimal> LoopMM { get; set; }

    public string LoopColor { get; set; }

    public Nullable<decimal> LoopAttachmentFree { get; set; }

    public Nullable<decimal> LoopAttachmentLong { get; set; }

    public Nullable<decimal> LoopAttachmentShort { get; set; }

    public Nullable<decimal> LinerWidth { get; set; }

    public Nullable<decimal> LinerHeight { get; set; }

    public Nullable<decimal> LinerMicron { get; set; }

    public Nullable<decimal> SWL { get; set; }

    public string SF { get; set; }

    public Nullable<decimal> TotalWt { get; set; }

    public Nullable<decimal> GrandTotal { get; set; }

    public Nullable<decimal> ReqWt { get; set; }

    public Nullable<decimal> ActWt { get; set; }

    public Nullable<decimal> DifWt { get; set; }

    public Nullable<decimal> FinishingCost { get; set; }

    public string CustomerSampleRec { get; set; }

    public string SampleSent { get; set; }

    public string PreviousPONumber { get; set; }

    public string Complaints { get; set; }

    public string PreparedBy { get; set; }

    public string CheckedBy { get; set; }

    public string ApprovedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> PO_Id { get; set; }

}

}
