
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class FIBC_ComponentDetails
{

    public int ComponentId { get; set; }

    public Nullable<int> JobCardId { get; set; }

    public string Loop1_Colour { get; set; }

    public Nullable<decimal> Loop1_Width { get; set; }

    public Nullable<decimal> Loop1_CutLength { get; set; }

    public Nullable<decimal> Loop1_GM { get; set; }

    public Nullable<decimal> Loop1_TotalPcs { get; set; }

    public Nullable<decimal> Loop1_CutWt { get; set; }

    public Nullable<decimal> Loop1_TotalKg { get; set; }

    public string Loop2_Colour { get; set; }

    public Nullable<decimal> Loop2_Width { get; set; }

    public Nullable<decimal> Loop2_CutLength { get; set; }

    public Nullable<decimal> Loop2_GM { get; set; }

    public Nullable<decimal> Loop2_TotalPcs { get; set; }

    public Nullable<decimal> Loop2_CutWt { get; set; }

    public Nullable<decimal> Loop2_TotalKg { get; set; }

    public string TopBend_Colour { get; set; }

    public Nullable<decimal> TopBend_Thickness { get; set; }

    public Nullable<decimal> TopBend_CutLength { get; set; }

    public Nullable<decimal> TopBend_TotalPcs { get; set; }

    public string TieCord_Colour { get; set; }

    public Nullable<decimal> TieCord_Width { get; set; }

    public Nullable<decimal> TieCord_CutLength { get; set; }

    public Nullable<decimal> TieCord_MTR { get; set; }

    public Nullable<decimal> TieCord_TotalPcs { get; set; }

    public Nullable<decimal> TieCord_CutWt { get; set; }

    public Nullable<decimal> TieCord_TotalKg { get; set; }

    public string RopeCord_Colour { get; set; }

    public Nullable<decimal> RopeCord_Width { get; set; }

    public Nullable<decimal> RopeCord_CutLength { get; set; }

    public Nullable<decimal> RopeCord_MTR { get; set; }

    public Nullable<decimal> RopeCord_TotalPcs { get; set; }

    public Nullable<decimal> RopeCord_CutWt { get; set; }

    public Nullable<decimal> RopeCord_TotalKg { get; set; }

    public string Liner_Type { get; set; }

    public Nullable<decimal> Liner_Width { get; set; }

    public Nullable<decimal> Liner_Height { get; set; }

    public Nullable<decimal> Liner_Micron { get; set; }

    public Nullable<decimal> Liner_TotalPcs { get; set; }

    public Nullable<decimal> Liner_CutWt { get; set; }

    public Nullable<decimal> Liner_TotalKg { get; set; }

    public string DOC_Type { get; set; }

    public Nullable<decimal> DOC_Width { get; set; }

    public Nullable<decimal> DOC_Length { get; set; }

    public Nullable<decimal> DOC_Micron { get; set; }

    public Nullable<decimal> DOC_TotalPcs { get; set; }

    public Nullable<decimal> DOC_CutWt { get; set; }

    public string Label_Type { get; set; }

    public string Label_Customer { get; set; }

    public Nullable<decimal> Label_CutWt { get; set; }

    public string ExtraLabel_Type { get; set; }

    public string ExtraLabel_Customer { get; set; }

    public Nullable<decimal> ExtraLabel_CutWt { get; set; }

    public string Shiftproof_Type { get; set; }

    public Nullable<decimal> Shiftproof_MTR { get; set; }

    public Nullable<decimal> Shiftproof_TotalStitch { get; set; }

    public Nullable<decimal> Shiftproof_CutWt { get; set; }

    public Nullable<decimal> Shiftproof_TotalKg { get; set; }

    public string Thread_Colour { get; set; }

    public Nullable<decimal> Thread_Width { get; set; }

    public Nullable<decimal> Thread_CutLength { get; set; }

    public Nullable<decimal> Thread_GM { get; set; }

    public Nullable<decimal> Thread_TotalPcs { get; set; }

    public Nullable<decimal> Thread_CutWt { get; set; }

    public Nullable<decimal> Thread_TotalKg { get; set; }

    public string BLock_Colour { get; set; }

    public Nullable<decimal> BLock_MTR { get; set; }

    public Nullable<decimal> BLock_TotalStitch { get; set; }

    public Nullable<decimal> BLock_CutWt { get; set; }

    public Nullable<decimal> BLock_TotalKg { get; set; }

    public Nullable<int> Print_NoOfColor { get; set; }

    public Nullable<int> Print_NoOfSide { get; set; }

    public string ExtraComp_Colour { get; set; }

    public Nullable<decimal> ExtraComp_Width { get; set; }

    public Nullable<decimal> ExtraComp_CutLength { get; set; }

    public Nullable<decimal> ExtraComp_GM { get; set; }

    public Nullable<decimal> ExtraComp_TotalPcs { get; set; }

    public Nullable<decimal> ExtraComp_CutWt { get; set; }

    public Nullable<decimal> ExtraComp_TotalKg { get; set; }

    public Nullable<decimal> TopBend_MTR { get; set; }

    public Nullable<decimal> TopBend_TotalKg { get; set; }

}

}
