//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCard_Details
    {
        public int JCD_Id { get; set; }
        public Nullable<int> JobCard_Id { get; set; }
        public string Item_No { get; set; }
        public string Item_Description { get; set; }
        public Nullable<int> Qty_Per_Bale { get; set; }
        public Nullable<int> Bale_Count { get; set; }
        public Nullable<int> Total_Quantity { get; set; }
        public string Unit { get; set; }
        public string Process_Type { get; set; }
        public Nullable<int> Completed_Qty { get; set; }
    }
}
