
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class JobCard_Master
{

    public int JobCard_Id { get; set; }

    public string JobCard_Number { get; set; }

    public Nullable<int> PO_Id { get; set; }

    public string PO_Number { get; set; }

    public Nullable<int> Vendor_Id { get; set; }

    public Nullable<int> Company_Id { get; set; }

    public Nullable<System.DateTime> Job_Date { get; set; }

    public string Buyer_Name { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

}

}
