
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class JobCard_Production_Tracking
{

    public int Tracking_Id { get; set; }

    public Nullable<int> JobCard_Id { get; set; }

    public Nullable<int> JCD_Id { get; set; }

    public string Operation_Name { get; set; }

    public Nullable<int> Input_Qty { get; set; }

    public Nullable<int> Output_Qty { get; set; }

    public Nullable<int> Wastage_Qty { get; set; }

    public string Machine_Name { get; set; }

    public Nullable<System.DateTime> Start_Time { get; set; }

    public Nullable<System.DateTime> End_Time { get; set; }

    public string Operator_Name { get; set; }

    public Nullable<int> Status { get; set; }

}

}
