
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class PurchaseOrder_Details
{

    public int POD_Id { get; set; }

    public int PO_Id { get; set; }

    public string Item_No { get; set; }

    public string Item_Description { get; set; }

    public Nullable<int> Qty_Per_Bale { get; set; }

    public Nullable<int> Bale_Count { get; set; }

    public Nullable<int> Total_Quantity { get; set; }

    public string Unit { get; set; }

    public Nullable<decimal> Unit_Price { get; set; }

    public Nullable<decimal> Line_Total { get; set; }

    public string Remarks { get; set; }



    public virtual PurchaseOrder PurchaseOrder { get; set; }

}

}
