
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class PurchaseOrder
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PurchaseOrder()
    {

        this.PurchaseOrder_Details = new HashSet<PurchaseOrder_Details>();

    }


    public int PO_Id { get; set; }

    public string PO_Number { get; set; }

    public System.DateTime PO_Date { get; set; }

    public int Vendor_Id { get; set; }

    public int Company_Id { get; set; }

    public string Buyer_Name { get; set; }

    public string Buyer_Phone { get; set; }

    public string Ship_Via { get; set; }

    public Nullable<System.DateTime> Receive_By_Date { get; set; }

    public string Payment_Terms { get; set; }

    public string Currency { get; set; }

    public Nullable<decimal> Sub_Total { get; set; }

    public Nullable<decimal> Tax_Amount { get; set; }

    public Nullable<decimal> Freight { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<decimal> Grand_Total { get; set; }

    public string PO_Status { get; set; }

    public string Approved_By { get; set; }

    public Nullable<System.DateTime> Approved_Date { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public Nullable<bool> Is_Active { get; set; }

    public Nullable<int> Status { get; set; }



    public virtual Company_Master Company_Master { get; set; }

    public virtual Vendor_Master Vendor_Master { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PurchaseOrder_Details> PurchaseOrder_Details { get; set; }

}

}
