//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDispatch
    {
        public int Dispatch_Id { get; set; }
        public Nullable<int> Sr_No { get; set; }
        public string Customer { get; set; }
        public string PO_Number { get; set; }
        public Nullable<int> PO_Id { get; set; }
        public string Size_Of_Bag { get; set; }
        public Nullable<decimal> Req_Wt { get; set; }
        public Nullable<decimal> Total_Req_Wt { get; set; }
        public Nullable<int> Actual_Quantity { get; set; }
        public Nullable<decimal> Act_Wt { get; set; }
        public Nullable<decimal> Total_Act_Wt { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Kg_Or_Pcs { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string Contractor { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Billing_Date { get; set; }
        public string Item_No { get; set; }
        public string Container_No { get; set; }
        public string ORDER_QTY { get; set; }
    }
}
