//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDispatchContractor
    {
        public int DisContr_Id { get; set; }
        public Nullable<int> Dispatch_Id { get; set; }
        public Nullable<int> Contractor_Id { get; set; }
        public string Contractor_Name { get; set; }
        public string Customer { get; set; }
        public string PO_Ref_No { get; set; }
        public string Size_Of_Bag { get; set; }
        public Nullable<int> Actual_Quantity { get; set; }
        public Nullable<decimal> Act_Wt { get; set; }
        public Nullable<decimal> Total_Wt { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Crate { get; set; }
        public string Kg_Or_Pcs { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
