
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tblPurchaseOrder
{

    public int PO_Id { get; set; }

    public System.DateTime Billing_Date { get; set; }

    public string Customer { get; set; }

    public string Container_No { get; set; }

    public string PO_Number { get; set; }

    public string Item_No { get; set; }

    public string Size_Of_Bag { get; set; }

    public string ORDER_QTY { get; set; }

    public Nullable<decimal> Req_Wt { get; set; }

    public Nullable<decimal> Total_Req_Wt { get; set; }

    public Nullable<decimal> Act_Wt { get; set; }

    public Nullable<decimal> Total_Act_Wt { get; set; }

    public Nullable<decimal> PcsPerPallet { get; set; }

    public string Attachment { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> Updated_Date { get; set; }

}

}
