//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsummaryreport
    {
        public int tblsummaryreport_id { get; set; }
        public Nullable<int> Contractor_id { get; set; }
        public string Contractor_Name { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Extra_Amt { get; set; }
        public Nullable<decimal> Non_Dispatch_Amt { get; set; }
        public Nullable<decimal> Total_Amt { get; set; }
        public Nullable<int> summary_month { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Belling_Amt { get; set; }
        public Nullable<bool> Is_Customor { get; set; }
    }
}
