
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tblVisitor
{

    public int Id { get; set; }

    public string FlatNo { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public string Photo { get; set; }

    public string Type { get; set; }

    public string Frequency { get; set; }

    public System.DateTime VisitDate { get; set; }

    public System.TimeSpan VisitTime { get; set; }

    public string VehicleNo { get; set; }

    public bool Consent { get; set; }

    public Nullable<int> CreateBy { get; set; }

    public System.DateTime CreateDate { get; set; }

    public string VisitorDetails { get; set; }

    public Nullable<int> NoOfPerson { get; set; }

}

}
