
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApptSoft.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Vendor_Master
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vendor_Master()
    {

        this.PurchaseOrders = new HashSet<PurchaseOrder>();

    }


    public int Vendor_Id { get; set; }

    public string Vendor_Name { get; set; }

    public string Contact_Person { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip_Code { get; set; }

    public string Country { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string GST_Number { get; set; }

    public Nullable<bool> Is_Active { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }

}

}
